version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "dependabot/central"
    schedule:
      interval: "monthly"
      day: "first"
    open-pull-requests-limit: 99
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"